### PR TITLE
More list recommendations

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**

### CODE REVIEW

**Comment by GiddyGoatGaming** [comment]
The unified host list was already in rethinkdns and I had a good experience with it so I recommend bringing it over here. Phishing army extended is a bit self explanatory, just an add on to the standard phishing army. Dandelion sprouts Nordic filter list is a little list but could be useful to certain people

**Comment by GiddyGoatGaming** [comment]
Just added inversion here because it is basically the list that google says “these are malicious sites”. Or what not

**Comment by bhanupratapys** [comment]
If you can make the recommended changes, then the list will be live in <10 minutes.

**Comment by GiddyGoatGaming** [comment]
> If you can make the recommended changes, then the list will be live in <10 minutes.

I’m not the most experienced with GitHub. Did you recommend changes?

**Comment by bhanupratapys** [comment]
> I’m not the most experienced with GitHub. Did you recommend changes?

It's okay, I'll do it myself 😅

**Pull request merged**
