### PR TITLE
Add Ultimate Hosts Blacklist

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist

It is a malware and phishing blocklist with 635,966 included domains.

### CODE REVIEW

**Comment by bhanupratapys** [comment]
Why do we need this when we have almost all of the sources which this list uses are already included in our setup?

https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#credits--thanks

**Comment by GiddyGoatGaming** [comment]
> Why do we need this when we have almost all of the sources which this list uses are already included in our setup?
> 
> https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#credits--thanks

For the same reason we include hagezi intelligence feeds. For the ease of blocklist selection. Also, they remove dead domains by default like hagezi’s

**Comment by bhanupratapys** [comment]
I'm thinking of strictly enforcing modular based approach for blocklists, so that size of blocklists doesn't balloon out of control. I'll try to clean up repo when I get time.

P.S, customfilter was always intended to use modular approach.

**Comment by GiddyGoatGaming** [comment]
> 

Ok sounds good. Il close this request now

**Pull request closed without merging**
