### PR TITLE
download.js: Improve the regex to be simpler and potentially more effective

### PR DESCRIPTION
**Pull request by SpencerIsGiddy**
This pr simplifies the regex to be more concise.

### CODE REVIEW

**Comment by SpencerIsGiddy** [comment]
I can’t seem to figure out why the test is failing. The functionality remains the same and the only change seems the be how the regex are written.

**Comment by bhanupratapys** [comment]
Regex is failing. You should be able to get this [result](https://github.com/dnswarden/blocklist-staging/blob/main/test_data/output.txt) from this [input](https://github.com/dnswarden/blocklist-staging/blob/main/test_data/input.txt)

**Comment by SpencerIsGiddy** [comment]
I’m going to close this as I try to figure something out. Because nothing seems to be working my way today with regexes

il reopen this once I figure out a solution

**Comment by bhanupratapys** [comment]
> I’m going to close this as I try to figure something out. Because nothing seems to be working my way today with regexes
> 
> il reopen this once I figure out a solution

Regex as of now is a 3 step process (firstReplace, secondReplace and domainMatch). Try to manipulate single step at a time and see whether it works or not.

**Pull request closed without merging**
