### PR TITLE
Add hagezi Ultimate list

### PR DESCRIPTION
**Pull request by GiddyGoatGaming**
Not sure if there’s a way to move this right under pro++ and above the threat intelligence feeds list but but right there would be great. I can move id’s around so it goes there if that’s possible. Anyways, hagezi ultimate has all the pro++ and threat intelligence feeds lists but adds onto that so it’s more aggressive. Not sure how that’s possible with the amount it had already but here we are. If there’s anything I can, just let me know

### CODE REVIEW

**Comment by bhanupratapys** [comment]
> Not sure if there’s a way to move this right under pro++ and above the threat intelligence feeds list but but right there would be great. I can move id’s around so it goes there if that’s possible.

Moving ID's breaks stuff internally and messes people's configuration, i don't want to deal with them :see_no_evil:

**Comment by bhanupratapys** [comment]
https://github.com/hagezi/dns-blocklists/discussions/83

Ultimate list is the newest addition, maybe wait for couple of weeks until it matures?

**Comment by GiddyGoatGaming** [comment]
Sure we can wait till it matures a bit more. I’m surprised Hagezi even created an ultimate since he made it seem like pro++ was aggressive (even though I found no faults with it)

**Comment by bhanupratapys** [comment]
I'm gonna close this and we can look into this in couple of weeks/months.

**Comment by GiddyGoatGaming** [comment]
Hello👋. Would you say enough time has passed to make a decision whether to add this list or not?

**Comment by bhanupratapys** [comment]
I'm gonna add this list when I'm done with #17

**Comment by GiddyGoatGaming** [comment]
> I'm gonna add this list when I'm done with #17

Perfect! If you can get wildcard entries with dnswarden, that will be so awesome!

**Comment by bhanupratapys** [comment]
> Perfect! If you can get wildcard entries with dnswarden, that will be so awesome!

Customfilter has supported wildcards from day 1, as of now they are basically limited to some of `nextdns` filters and `nickspaargaren (no-google)` . 😬

**Comment by GiddyGoatGaming** [comment]
> > Perfect! If you can get wildcard entries with dnswarden, that will be so awesome!
> 
> Customfilter has supported wildcards from day 1, as of now they are basically limited to some of `nextdns` filters and `nickspaargaren (no-google)` . 😬

Oh yeah, I forgot about the “wildcards being supported but slow down the experience if too many are used rule”. Will this change in the future so it will be negligible no matter how many are used?

**Pull request closed without merging**
